-- Fixes a live Supabase security advisory (Auth/Database Advisors,
-- "RLS Disabled in Public", ERROR level, first surfaced 2026-08-31 and
-- re-confirmed live via `supabase db advisors --linked` on 2026-09-04):
--
--   Table `public.spatial_ref_sys` is public, but RLS has not been enabled.
--
-- Apply with `supabase db push --linked` (CLI-managed, same convention as
-- every other migration in this repo — see 20260903120000_tile_coverage.sql's
-- header for why SQL-editor instructions elsewhere are stale).
--
-- WHAT THIS TABLE IS. `spatial_ref_sys` is not an application table — it is
-- created automatically by `CREATE EXTENSION postgis` (applied in this
-- project's very first migration) and holds ~8,500 rows of public spatial
-- reference system definitions (SRIDs — e.g. WGS84 is 4326), the lookup
-- table PostGIS's own geometry functions (ST_Transform, etc.) consult
-- internally. It is not something this app's client code ever queries
-- directly, and it was never covered by this repo's own RLS-enabling
-- migrations because it isn't one of our tables — it just inherited
-- PostGIS's default of no RLS, which the advisor correctly flags: any table
-- exposed to PostgREST without RLS is, by default, readable AND WRITABLE by
-- anyone holding the project's anon key (which ships in the app bundle,
-- so "anyone" really does mean anyone).
--
-- WHY THIS MATTERS IN PRACTICE, EVEN THOUGH THE DATA ITSELF IS PUBLIC. The
-- content isn't sensitive (SRID definitions are the same for every Postgres/
-- PostGIS install on earth), but the exposure isn't just read: without RLS,
-- an anonymous client can also `DELETE FROM spatial_ref_sys` or corrupt rows
-- via the REST API. PostGIS functions used elsewhere in this project
-- (ST_Distance/ST_MakePoint in flag_implausible_speed, ST_Difference in
-- apply_territory_overlap, the isoperimetric fence-forgery guard) all
-- resolve SRIDs through this table — deleting or altering rows here would
-- break geometry operations project-wide, not leak anything.
--
-- THE FIX. Enable RLS, and add a single permissive SELECT policy: the data
-- is genuinely public reference data (every Postgres/PostGIS install ships
-- the identical table), so restricting reads would only break something for
-- no security benefit. No INSERT/UPDATE/DELETE policy is added, which under
-- RLS means those stay blocked for every role that isn't exempt from RLS —
-- Supabase's own service_role and the underlying postgres/supabase_admin
-- roles carry BYPASSRLS and are unaffected, so PostGIS's own internal
-- lookups (which run as the table owner, not through PostgREST) keep
-- working exactly as before. This is Supabase's own documented remediation
-- for this exact advisory (linked in the advisor output):
-- https://supabase.com/docs/guides/database/database-linter?lint=0013_rls_disabled_in_public

alter table public.spatial_ref_sys enable row level security;

create policy "spatial_ref_sys: read all" on public.spatial_ref_sys
  for select using (true);

-- ============================================================================
-- Other findings from the same `supabase db advisors --linked` run,
-- DELIBERATELY NOT fixed here — recorded so they aren't lost, not silently
-- resolved. See the surveyor's report to Pedro for the full list; the one
-- worth a closer look before deciding anything is:
--
--   `public.apply_territory_overlap()` (Phase 3's cross-user overlap
--   trigger function) is SECURITY DEFINER and is directly callable by BOTH
--   the anon and authenticated roles via `/rest/v1/rpc/apply_territory_overlap`
--   — i.e. outside the normal "insert a run, the trigger fires" path this
--   function was written for. Whether that RPC exposure is intentional
--   (should never be, for a trigger function) or just an artifact of how
--   Postgres exposes SECURITY DEFINER functions to PostgREST by default is
--   NOT resolved by this migration — fixing it needs to confirm what
--   privilege apply_territory_overlap actually needs (it writes to OTHER
--   users' rows during overlap resolution, which is presumably why it's
--   DEFINER and not INVOKER in the first place) before revoking EXECUTE or
--   changing its security context, so it isn't a same-risk-level fix as the
--   one-line change above.
-- ============================================================================
